// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzija6i1EOAoiKg8Wb_93-judtMla45lE',
    appId: '1:493122296588:web:d4ee4184fd4504c6d60729',
    messagingSenderId: '493122296588',
    projectId: 'projeto-flutter-infnet-2025-2',
    authDomain: 'projeto-flutter-infnet-2025-2.firebaseapp.com',
    storageBucket: 'projeto-flutter-infnet-2025-2.firebasestorage.app',
    measurementId: 'G-M7SES5T3ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJL3T9Gn4DR53B7fuMmQ5QAun639w0uro',
    appId: '1:493122296588:android:ba7b703aef85aaf1d60729',
    messagingSenderId: '493122296588',
    projectId: 'projeto-flutter-infnet-2025-2',
    storageBucket: 'projeto-flutter-infnet-2025-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNlhKaz7Rd2CiSCYjI-ehlOUHo_sWHIE',
    appId: '1:493122296588:ios:d60a3a327e63aa9dd60729',
    messagingSenderId: '493122296588',
    projectId: 'projeto-flutter-infnet-2025-2',
    storageBucket: 'projeto-flutter-infnet-2025-2.firebasestorage.app',
    iosBundleId: 'com.example.projetoflutterinfnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNlhKaz7Rd2CiSCYjI-ehlOUHo_sWHIE',
    appId: '1:493122296588:ios:d60a3a327e63aa9dd60729',
    messagingSenderId: '493122296588',
    projectId: 'projeto-flutter-infnet-2025-2',
    storageBucket: 'projeto-flutter-infnet-2025-2.firebasestorage.app',
    iosBundleId: 'com.example.projetoflutterinfnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzija6i1EOAoiKg8Wb_93-judtMla45lE',
    appId: '1:493122296588:web:8a340c5baf4891a5d60729',
    messagingSenderId: '493122296588',
    projectId: 'projeto-flutter-infnet-2025-2',
    authDomain: 'projeto-flutter-infnet-2025-2.firebaseapp.com',
    storageBucket: 'projeto-flutter-infnet-2025-2.firebasestorage.app',
    measurementId: 'G-2TTR0GMJZR',
  );
}
